// Package clients provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package clients

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Balance defines model for Balance.
type Balance struct {
	Balance int `json:"balance"`
}

// Error defines model for Error.
type Error struct {
	Details *[]ErrorDetail `json:"details,omitempty"`
	Message string         `json:"message"`
	Slug    string         `json:"slug"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  *string `json:"error_slug,omitempty"`
	Message    *string `json:"message,omitempty"`
}

// OnboardUserRequest defines model for OnboardUserRequest.
type OnboardUserRequest struct {
	DisplayName string `json:"displayName"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`

	// Total Number of items across all pages
	Total int `json:"total"`
}

// TopUpRequest defines model for TopUpRequest.
type TopUpRequest struct {
	Amount int `json:"amount"`
}

// Trainer defines model for Trainer.
type Trainer struct {
	Balance     int    `json:"balance"`
	DisplayName string `json:"displayName"`
	Uuid        string `json:"uuid"`
}

// TrainersPage defines model for TrainersPage.
type TrainersPage struct {
	Items      []Trainer  `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// Conflict defines model for Conflict.
type Conflict = Error

// InvalidInput defines model for InvalidInput.
type InvalidInput = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetTrainersParams defines parameters for GetTrainers.
type GetTrainersParams struct {
	// Page Page number, starting at 1
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of trainers per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// TopUpBalanceJSONRequestBody defines body for TopUpBalance for application/json ContentType.
type TopUpBalanceJSONRequestBody = TopUpRequest

// OnboardUserJSONRequestBody defines body for OnboardUser for application/json ContentType.
type OnboardUserJSONRequestBody = OnboardUserRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetTrainers Get the trainers
	//
	// Returns the trainers ordered by display name. The list is paginated with `page` and `pageSize`; `total` is the number of trainers across all pages.
	//
	// Corresponds with GET /api/v1/trainers (the `GetTrainers` operationId).
	GetTrainers(ctx context.Context, params *GetTrainersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TopUpBalanceWithBody Top up the balance of the session user
	//
	// Adds `amount` to the balance of the user from the session and returns the new balance. There is no payment step yet.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/users/balance/top-up (the `TopUpBalance` operationId).
	TopUpBalanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TopUpBalance Top up the balance of the session user
	//
	// Adds `amount` to the balance of the user from the session and returns the new balance. There is no payment step yet.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/users/balance/top-up (the `TopUpBalance` operationId).
	TopUpBalance(ctx context.Context, body TopUpBalanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OnboardUserWithBody Onboard the user from the session
	//
	// Creates the user from the session (uuid and role), with a zero balance. The role is the session's trainer or attendee role.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/users/onboard (the `OnboardUser` operationId).
	OnboardUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OnboardUser Onboard the user from the session
	//
	// Creates the user from the session (uuid and role), with a zero balance. The role is the session's trainer or attendee role.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/users/onboard (the `OnboardUser` operationId).
	OnboardUser(ctx context.Context, body OnboardUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetTrainers Get the trainers
//
// Returns the trainers ordered by display name. The list is paginated with `page` and `pageSize`; `total` is the number of trainers across all pages.
//
// Corresponds with GET /api/v1/trainers (the `GetTrainers` operationId).
func (c *Client) GetTrainers(ctx context.Context, params *GetTrainersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTrainersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// TopUpBalanceWithBody Top up the balance of the session user
//
// Adds `amount` to the balance of the user from the session and returns the new balance. There is no payment step yet.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/users/balance/top-up (the `TopUpBalance` operationId).
func (c *Client) TopUpBalanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTopUpBalanceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// TopUpBalance Top up the balance of the session user
//
// Adds `amount` to the balance of the user from the session and returns the new balance. There is no payment step yet.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/users/balance/top-up (the `TopUpBalance` operationId).
func (c *Client) TopUpBalance(ctx context.Context, body TopUpBalanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTopUpBalanceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// OnboardUserWithBody Onboard the user from the session
//
// Creates the user from the session (uuid and role), with a zero balance. The role is the session's trainer or attendee role.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/users/onboard (the `OnboardUser` operationId).
func (c *Client) OnboardUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOnboardUserRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// OnboardUser Onboard the user from the session
//
// Creates the user from the session (uuid and role), with a zero balance. The role is the session's trainer or attendee role.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/users/onboard (the `OnboardUser` operationId).
func (c *Client) OnboardUser(ctx context.Context, body OnboardUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOnboardUserRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetTrainersRequest constructs an http.Request for the GetTrainers method
func NewGetTrainersRequest(server string, params *GetTrainersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/trainers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pageSize", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTopUpBalanceRequest calls the generic TopUpBalance builder with application/json body
func NewTopUpBalanceRequest(server string, body TopUpBalanceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTopUpBalanceRequestWithBody(server, "application/json", bodyReader)
}

// NewTopUpBalanceRequestWithBody constructs an http.Request for the TopUpBalance method, with any body, and a specified content type
func NewTopUpBalanceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/users/balance/top-up")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewOnboardUserRequest calls the generic OnboardUser builder with application/json body
func NewOnboardUserRequest(server string, body OnboardUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOnboardUserRequestWithBody(server, "application/json", bodyReader)
}

// NewOnboardUserRequestWithBody constructs an http.Request for the OnboardUser method, with any body, and a specified content type
func NewOnboardUserRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/users/onboard")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetTrainersWithResponse Get the trainers
	//
	// Returns the trainers ordered by display name. The list is paginated with `page` and `pageSize`; `total` is the number of trainers across all pages.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/trainers (the `GetTrainers` operationId).
	GetTrainersWithResponse(ctx context.Context, params *GetTrainersParams, reqEditors ...RequestEditorFn) (*GetTrainersClientResponse, error)

	// TopUpBalanceWithBodyWithResponse Top up the balance of the session user
	//
	// Adds `amount` to the balance of the user from the session and returns the new balance. There is no payment step yet.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/users/balance/top-up (the `TopUpBalance` operationId).
	TopUpBalanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TopUpBalanceClientResponse, error)

	// TopUpBalanceWithResponse Top up the balance of the session user
	//
	// Adds `amount` to the balance of the user from the session and returns the new balance. There is no payment step yet.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/users/balance/top-up (the `TopUpBalance` operationId).
	TopUpBalanceWithResponse(ctx context.Context, body TopUpBalanceJSONRequestBody, reqEditors ...RequestEditorFn) (*TopUpBalanceClientResponse, error)

	// OnboardUserWithBodyWithResponse Onboard the user from the session
	//
	// Creates the user from the session (uuid and role), with a zero balance. The role is the session's trainer or attendee role.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/users/onboard (the `OnboardUser` operationId).
	OnboardUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OnboardUserClientResponse, error)

	// OnboardUserWithResponse Onboard the user from the session
	//
	// Creates the user from the session (uuid and role), with a zero balance. The role is the session's trainer or attendee role.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/users/onboard (the `OnboardUser` operationId).
	OnboardUserWithResponse(ctx context.Context, body OnboardUserJSONRequestBody, reqEditors ...RequestEditorFn) (*OnboardUserClientResponse, error)
}

type GetTrainersClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *TrainersPage
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidInput
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetTrainersClientResponse) GetJSON200() *TrainersPage {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetTrainersClientResponse) GetJSON400() *InvalidInput {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetTrainersClientResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r GetTrainersClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetTrainersClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTrainersClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTrainersClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TopUpBalanceClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Balance
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidInput
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r TopUpBalanceClientResponse) GetJSON200() *Balance {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r TopUpBalanceClientResponse) GetJSON400() *InvalidInput {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r TopUpBalanceClientResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r TopUpBalanceClientResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r TopUpBalanceClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r TopUpBalanceClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TopUpBalanceClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TopUpBalanceClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type OnboardUserClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidInput
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r OnboardUserClientResponse) GetJSON400() *InvalidInput {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r OnboardUserClientResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r OnboardUserClientResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r OnboardUserClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r OnboardUserClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OnboardUserClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r OnboardUserClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetTrainersWithResponse Get the trainers
//
// Returns the trainers ordered by display name. The list is paginated with `page` and `pageSize`; `total` is the number of trainers across all pages.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/trainers (the `GetTrainers` operationId).
func (c *ClientWithResponses) GetTrainersWithResponse(ctx context.Context, params *GetTrainersParams, reqEditors ...RequestEditorFn) (*GetTrainersClientResponse, error) {
	rsp, err := c.GetTrainers(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTrainersClientResponse(rsp)
}

// TopUpBalanceWithBodyWithResponse Top up the balance of the session user
//
// Adds `amount` to the balance of the user from the session and returns the new balance. There is no payment step yet.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/users/balance/top-up (the `TopUpBalance` operationId).
func (c *ClientWithResponses) TopUpBalanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TopUpBalanceClientResponse, error) {
	rsp, err := c.TopUpBalanceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTopUpBalanceClientResponse(rsp)
}

// TopUpBalanceWithResponse Top up the balance of the session user
//
// Adds `amount` to the balance of the user from the session and returns the new balance. There is no payment step yet.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/users/balance/top-up (the `TopUpBalance` operationId).
func (c *ClientWithResponses) TopUpBalanceWithResponse(ctx context.Context, body TopUpBalanceJSONRequestBody, reqEditors ...RequestEditorFn) (*TopUpBalanceClientResponse, error) {
	rsp, err := c.TopUpBalance(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTopUpBalanceClientResponse(rsp)
}

// OnboardUserWithBodyWithResponse Onboard the user from the session
//
// Creates the user from the session (uuid and role), with a zero balance. The role is the session's trainer or attendee role.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/users/onboard (the `OnboardUser` operationId).
func (c *ClientWithResponses) OnboardUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OnboardUserClientResponse, error) {
	rsp, err := c.OnboardUserWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOnboardUserClientResponse(rsp)
}

// OnboardUserWithResponse Onboard the user from the session
//
// Creates the user from the session (uuid and role), with a zero balance. The role is the session's trainer or attendee role.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/users/onboard (the `OnboardUser` operationId).
func (c *ClientWithResponses) OnboardUserWithResponse(ctx context.Context, body OnboardUserJSONRequestBody, reqEditors ...RequestEditorFn) (*OnboardUserClientResponse, error) {
	rsp, err := c.OnboardUser(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOnboardUserClientResponse(rsp)
}

// ParseGetTrainersClientResponse parses an HTTP response from a GetTrainersWithResponse call
func ParseGetTrainersClientResponse(rsp *http.Response) (*GetTrainersClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTrainersClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TrainersPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidInput
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseTopUpBalanceClientResponse parses an HTTP response from a TopUpBalanceWithResponse call
func ParseTopUpBalanceClientResponse(rsp *http.Response) (*TopUpBalanceClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TopUpBalanceClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Balance
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidInput
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseOnboardUserClientResponse parses an HTTP response from a OnboardUserWithResponse call
func ParseOnboardUserClientResponse(rsp *http.Response) (*OnboardUserClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OnboardUserClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidInput
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}
