// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package http

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
)

// Balance defines model for Balance.
type Balance struct {
	Balance int `json:"balance"`
}

// Error defines model for Error.
type Error struct {
	Details *[]ErrorDetail `json:"details,omitempty"`
	Message string         `json:"message"`
	Slug    string         `json:"slug"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  *string `json:"error_slug,omitempty"`
	Message    *string `json:"message,omitempty"`
}

// OnboardUserRequest defines model for OnboardUserRequest.
type OnboardUserRequest struct {
	DisplayName string `json:"displayName"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`

	// Total Number of items across all pages
	Total int `json:"total"`
}

// TopUpRequest defines model for TopUpRequest.
type TopUpRequest struct {
	Amount int `json:"amount"`
}

// Trainer defines model for Trainer.
type Trainer struct {
	Balance     int    `json:"balance"`
	DisplayName string `json:"displayName"`
	Uuid        string `json:"uuid"`
}

// TrainersPage defines model for TrainersPage.
type TrainersPage struct {
	Items      []Trainer  `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// Conflict defines model for Conflict.
type Conflict = Error

// InvalidInput defines model for InvalidInput.
type InvalidInput = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetTrainersParams defines parameters for GetTrainers.
type GetTrainersParams struct {
	// Page Page number, starting at 1
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of trainers per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// TopUpBalanceJSONRequestBody defines body for TopUpBalance for application/json ContentType.
type TopUpBalanceJSONRequestBody = TopUpRequest

// OnboardUserJSONRequestBody defines body for OnboardUser for application/json ContentType.
type OnboardUserJSONRequestBody = OnboardUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetTrainers Get the trainers
	// (GET /api/v1/trainers)
	GetTrainers(ctx *echo.Context, params GetTrainersParams) error
	// TopUpBalance Top up the balance of the session user
	// (POST /api/v1/users/balance/top-up)
	TopUpBalance(ctx *echo.Context) error
	// OnboardUser Onboard the user from the session
	// (POST /api/v1/users/onboard)
	OnboardUser(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetTrainers converts echo context to params.
func (w *ServerInterfaceWrapper) GetTrainers(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTrainersParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", ctx.QueryParams(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageSize: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTrainers(ctx, params)
	return err
}

// TopUpBalance converts echo context to params.
func (w *ServerInterfaceWrapper) TopUpBalance(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TopUpBalance(ctx)
	return err
}

// OnboardUser converts echo context to params.
func (w *ServerInterfaceWrapper) OnboardUser(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OnboardUser(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/api/v1/trainers", wrapper.GetTrainers, options.OperationMiddlewares["getTrainers"]...)
	router.POST(options.BaseURL+"/api/v1/users/onboard", wrapper.OnboardUser, options.OperationMiddlewares["onboardUser"]...)
	router.POST(options.BaseURL+"/api/v1/users/balance/top-up", wrapper.TopUpBalance, options.OperationMiddlewares["topUpBalance"]...)

}

type ConflictJSONResponse Error

type InvalidInputJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type GetTrainersRequestObject struct {
	Params GetTrainersParams
}

type GetTrainersResponseObject interface {
	VisitGetTrainersResponse(w http.ResponseWriter) error
}

type GetTrainers200JSONResponse TrainersPage

func (response GetTrainers200JSONResponse) VisitGetTrainersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTrainers400JSONResponse struct{ InvalidInputJSONResponse }

func (response GetTrainers400JSONResponse) VisitGetTrainersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTrainers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetTrainers401JSONResponse) VisitGetTrainersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type TopUpBalanceRequestObject struct {
	Body *TopUpBalanceJSONRequestBody
}

type TopUpBalanceResponseObject interface {
	VisitTopUpBalanceResponse(w http.ResponseWriter) error
}

type TopUpBalance200JSONResponse Balance

func (response TopUpBalance200JSONResponse) VisitTopUpBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type TopUpBalance400JSONResponse struct{ InvalidInputJSONResponse }

func (response TopUpBalance400JSONResponse) VisitTopUpBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type TopUpBalance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response TopUpBalance401JSONResponse) VisitTopUpBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type TopUpBalance404JSONResponse struct{ NotFoundJSONResponse }

func (response TopUpBalance404JSONResponse) VisitTopUpBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type OnboardUserRequestObject struct {
	Body *OnboardUserJSONRequestBody
}

type OnboardUserResponseObject interface {
	VisitOnboardUserResponse(w http.ResponseWriter) error
}

type OnboardUser204Response struct {
}

func (response OnboardUser204Response) VisitOnboardUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type OnboardUser400JSONResponse struct{ InvalidInputJSONResponse }

func (response OnboardUser400JSONResponse) VisitOnboardUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type OnboardUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response OnboardUser401JSONResponse) VisitOnboardUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type OnboardUser409JSONResponse struct{ ConflictJSONResponse }

func (response OnboardUser409JSONResponse) VisitOnboardUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetTrainers Get the trainers
	// (GET /api/v1/trainers)
	GetTrainers(ctx context.Context, request GetTrainersRequestObject) (GetTrainersResponseObject, error)
	// TopUpBalance Top up the balance of the session user
	// (POST /api/v1/users/balance/top-up)
	TopUpBalance(ctx context.Context, request TopUpBalanceRequestObject) (TopUpBalanceResponseObject, error)
	// OnboardUser Onboard the user from the session
	// (POST /api/v1/users/onboard)
	OnboardUser(ctx context.Context, request OnboardUserRequestObject) (OnboardUserResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetTrainers operation middleware
func (sh *strictHandler) GetTrainers(ctx *echo.Context, params GetTrainersParams) error {
	var request GetTrainersRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTrainers(ctx.Request().Context(), request.(GetTrainersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTrainers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTrainersResponseObject); ok {
		return validResponse.VisitGetTrainersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// TopUpBalance operation middleware
func (sh *strictHandler) TopUpBalance(ctx *echo.Context) error {
	var request TopUpBalanceRequestObject

	var body TopUpBalanceJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.TopUpBalance(ctx.Request().Context(), request.(TopUpBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TopUpBalance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(TopUpBalanceResponseObject); ok {
		return validResponse.VisitTopUpBalanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// OnboardUser operation middleware
func (sh *strictHandler) OnboardUser(ctx *echo.Context) error {
	var request OnboardUserRequestObject

	var body OnboardUserJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OnboardUser(ctx.Request().Context(), request.(OnboardUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OnboardUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(OnboardUserResponseObject); ok {
		return validResponse.VisitOnboardUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
