// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbmodels

import (
	"context"
)

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, display_name, balance, role
FROM users.users
WHERE id = $1
`

func (q *Queries) GetUserByUUID(ctx context.Context, id string) (UsersUser, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, id)
	var i UsersUser
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Balance,
		&i.Role,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users.users (id, display_name, balance, role)
VALUES ($1, $2, $3, $4)
`

type InsertUserParams struct {
	ID          string
	DisplayName string
	Balance     int32
	Role        string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.DisplayName,
		arg.Balance,
		arg.Role,
	)
	return err
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE users.users
SET balance = balance + $1::integer
WHERE id = $2 AND balance + $1::integer >= 0
RETURNING balance
`

type UpdateBalanceParams struct {
	AmountChange int32
	ID           string
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateBalance, arg.AmountChange, arg.ID)
	var balance int32
	err := row.Scan(&balance)
	return balance, err
}
