// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_read_model.sql

package dbmodels

import (
	"context"
)

const countTrainers = `-- name: CountTrainers :one
SELECT count(*)
FROM users.users
WHERE role = 'trainer'
`

func (q *Queries) CountTrainers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTrainers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTrainers = `-- name: GetTrainers :many
SELECT id, display_name, balance
FROM users.users
WHERE role = 'trainer'
ORDER BY display_name, id
LIMIT $2::bigint
OFFSET $1::bigint
`

type GetTrainersParams struct {
	PageOffset int64
	PageLimit  int64
}

type GetTrainersRow struct {
	ID          string
	DisplayName string
	Balance     int32
}

func (q *Queries) GetTrainers(ctx context.Context, arg GetTrainersParams) ([]GetTrainersRow, error) {
	rows, err := q.db.Query(ctx, getTrainers, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTrainersRow{}
	for rows.Next() {
		var i GetTrainersRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
