// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hours.sql

package dbmodels

import (
	"context"
	"time"
)

const getHours = `-- name: GetHours :many
SELECT trainer_uuid, hour, status
FROM trainers.hours
WHERE trainer_uuid = $1
    AND hour = ANY($2::timestamptz[])
`

type GetHoursParams struct {
	TrainerUuid string
	Hours       []time.Time
}

func (q *Queries) GetHours(ctx context.Context, arg GetHoursParams) ([]TrainersHour, error) {
	rows, err := q.db.Query(ctx, getHours, arg.TrainerUuid, arg.Hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainersHour{}
	for rows.Next() {
		var i TrainersHour
		if err := rows.Scan(&i.TrainerUuid, &i.Hour, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHours = `-- name: UpsertHours :exec
INSERT INTO trainers.hours (trainer_uuid, hour, status)
SELECT
    $1::text,
    unnest($2::timestamptz[]),
    unnest($3::text[])::trainers.hour_status
ON CONFLICT (trainer_uuid, hour)
DO UPDATE
SET status = EXCLUDED.status
`

type UpsertHoursParams struct {
	TrainerUuid string
	Hours       []time.Time
	Status      []string
}

func (q *Queries) UpsertHours(ctx context.Context, arg UpsertHoursParams) error {
	_, err := q.db.Exec(ctx, upsertHours, arg.TrainerUuid, arg.Hours, arg.Status)
	return err
}
