// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hours_read_model.sql

package dbmodels

import (
	"context"
	"time"
)

const getHoursInRange = `-- name: GetHoursInRange :many
SELECT trainer_uuid, hour, status
FROM trainers.hours
WHERE trainer_uuid = $1
    AND hour >= $2::timestamptz
    AND hour < $3::timestamptz
ORDER BY hour
`

type GetHoursInRangeParams struct {
	TrainerUuid string
	DateFrom    time.Time
	DateTo      time.Time
}

func (q *Queries) GetHoursInRange(ctx context.Context, arg GetHoursInRangeParams) ([]TrainersHour, error) {
	rows, err := q.db.Query(ctx, getHoursInRange, arg.TrainerUuid, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainersHour{}
	for rows.Next() {
		var i TrainersHour
		if err := rows.Scan(&i.TrainerUuid, &i.Hour, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
