// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmodels

import (
	"database/sql/driver"
	"fmt"
	"time"

	"backend/internal/trainers/domain"
)

type TrainersHourStatus string

const (
	TrainersHourStatusAvailability      TrainersHourStatus = "availability"
	TrainersHourStatusNotAvailability   TrainersHourStatus = "not-availability"
	TrainersHourStatusTrainingScheduled TrainersHourStatus = "training-scheduled"
)

func (e *TrainersHourStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrainersHourStatus(s)
	case string:
		*e = TrainersHourStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TrainersHourStatus: %T", src)
	}
	return nil
}

type NullTrainersHourStatus struct {
	TrainersHourStatus TrainersHourStatus
	Valid              bool // Valid is true if TrainersHourStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrainersHourStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TrainersHourStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrainersHourStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrainersHourStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrainersHourStatus), nil
}

type TrainersHour struct {
	TrainerUuid string
	Hour        time.Time
	Status      domain.HourStatus
}
