// Package clients provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package clients

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"backend/internal/trainers/domain"

	"github.com/oapi-codegen/runtime"
)

// Date defines model for Date.
type Date struct {
	Date         time.Time `json:"date"`
	HasFreeHours bool      `json:"hasFreeHours"`
	Hours        []Hour    `json:"hours"`
}

// Error defines model for Error.
type Error struct {
	Details *[]ErrorDetail `json:"details,omitempty"`
	Message string         `json:"message"`
	Slug    string         `json:"slug"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  *string `json:"error_slug,omitempty"`
	Message    *string `json:"message,omitempty"`
}

// Hour defines model for Hour.
type Hour struct {
	Hour   time.Time  `json:"hour"`
	Status HourStatus `json:"status"`
}

// HourStatus defines model for HourStatus.
type HourStatus = domain.HourStatus

// HoursRequest defines model for HoursRequest.
type HoursRequest struct {
	Hours []time.Time `json:"hours"`
}

// Conflict defines model for Conflict.
type Conflict = Error

// InvalidInput defines model for InvalidInput.
type InvalidInput = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Hours defines model for Hours.
type Hours = HoursRequest

// GetTrainerHoursParams defines parameters for GetTrainerHours.
type GetTrainerHoursParams struct {
	From time.Time `form:"from" json:"from"`
	To   time.Time `form:"to" json:"to"`
}

// MakeHoursAvailableJSONRequestBody defines body for MakeHoursAvailable for application/json ContentType.
type MakeHoursAvailableJSONRequestBody = HoursRequest

// MakeHoursNotAvailableJSONRequestBody defines body for MakeHoursNotAvailable for application/json ContentType.
type MakeHoursNotAvailableJSONRequestBody = HoursRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetTrainerHours Get the trainer's hours in a date range
	//
	// Returns every day from `from` to `to` (both inclusive, in UTC), each with all the hours between the minimum and maximum UTC hour. Hours that are not stored are returned as not available.
	//
	// Corresponds with GET /api/v1/trainer/hours (the `GetTrainerHours` operationId).
	GetTrainerHours(ctx context.Context, params *GetTrainerHoursParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MakeHoursAvailableWithBody Make hours available
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /api/v1/trainer/hours/available (the `MakeHoursAvailable` operationId).
	MakeHoursAvailableWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MakeHoursAvailable Make hours available
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /api/v1/trainer/hours/available (the `MakeHoursAvailable` operationId).
	MakeHoursAvailable(ctx context.Context, body MakeHoursAvailableJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MakeHoursNotAvailableWithBody Make hours not available
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /api/v1/trainer/hours/not-available (the `MakeHoursNotAvailable` operationId).
	MakeHoursNotAvailableWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MakeHoursNotAvailable Make hours not available
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /api/v1/trainer/hours/not-available (the `MakeHoursNotAvailable` operationId).
	MakeHoursNotAvailable(ctx context.Context, body MakeHoursNotAvailableJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetTrainerHours Get the trainer's hours in a date range
//
// Returns every day from `from` to `to` (both inclusive, in UTC), each with all the hours between the minimum and maximum UTC hour. Hours that are not stored are returned as not available.
//
// Corresponds with GET /api/v1/trainer/hours (the `GetTrainerHours` operationId).
func (c *Client) GetTrainerHours(ctx context.Context, params *GetTrainerHoursParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTrainerHoursRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MakeHoursAvailableWithBody Make hours available
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /api/v1/trainer/hours/available (the `MakeHoursAvailable` operationId).
func (c *Client) MakeHoursAvailableWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMakeHoursAvailableRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MakeHoursAvailable Make hours available
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /api/v1/trainer/hours/available (the `MakeHoursAvailable` operationId).
func (c *Client) MakeHoursAvailable(ctx context.Context, body MakeHoursAvailableJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMakeHoursAvailableRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MakeHoursNotAvailableWithBody Make hours not available
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /api/v1/trainer/hours/not-available (the `MakeHoursNotAvailable` operationId).
func (c *Client) MakeHoursNotAvailableWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMakeHoursNotAvailableRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MakeHoursNotAvailable Make hours not available
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /api/v1/trainer/hours/not-available (the `MakeHoursNotAvailable` operationId).
func (c *Client) MakeHoursNotAvailable(ctx context.Context, body MakeHoursNotAvailableJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMakeHoursNotAvailableRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetTrainerHoursRequest constructs an http.Request for the GetTrainerHours method
func NewGetTrainerHoursRequest(server string, params *GetTrainerHoursParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/trainer/hours")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "from", params.From, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "to", params.To, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewMakeHoursAvailableRequest calls the generic MakeHoursAvailable builder with application/json body
func NewMakeHoursAvailableRequest(server string, body MakeHoursAvailableJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMakeHoursAvailableRequestWithBody(server, "application/json", bodyReader)
}

// NewMakeHoursAvailableRequestWithBody constructs an http.Request for the MakeHoursAvailable method, with any body, and a specified content type
func NewMakeHoursAvailableRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/trainer/hours/available")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewMakeHoursNotAvailableRequest calls the generic MakeHoursNotAvailable builder with application/json body
func NewMakeHoursNotAvailableRequest(server string, body MakeHoursNotAvailableJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMakeHoursNotAvailableRequestWithBody(server, "application/json", bodyReader)
}

// NewMakeHoursNotAvailableRequestWithBody constructs an http.Request for the MakeHoursNotAvailable method, with any body, and a specified content type
func NewMakeHoursNotAvailableRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/trainer/hours/not-available")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetTrainerHoursWithResponse Get the trainer's hours in a date range
	//
	// Returns every day from `from` to `to` (both inclusive, in UTC), each with all the hours between the minimum and maximum UTC hour. Hours that are not stored are returned as not available.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/trainer/hours (the `GetTrainerHours` operationId).
	GetTrainerHoursWithResponse(ctx context.Context, params *GetTrainerHoursParams, reqEditors ...RequestEditorFn) (*GetTrainerHoursClientResponse, error)

	// MakeHoursAvailableWithBodyWithResponse Make hours available
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/trainer/hours/available (the `MakeHoursAvailable` operationId).
	MakeHoursAvailableWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MakeHoursAvailableClientResponse, error)

	// MakeHoursAvailableWithResponse Make hours available
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/trainer/hours/available (the `MakeHoursAvailable` operationId).
	MakeHoursAvailableWithResponse(ctx context.Context, body MakeHoursAvailableJSONRequestBody, reqEditors ...RequestEditorFn) (*MakeHoursAvailableClientResponse, error)

	// MakeHoursNotAvailableWithBodyWithResponse Make hours not available
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/trainer/hours/not-available (the `MakeHoursNotAvailable` operationId).
	MakeHoursNotAvailableWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MakeHoursNotAvailableClientResponse, error)

	// MakeHoursNotAvailableWithResponse Make hours not available
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /api/v1/trainer/hours/not-available (the `MakeHoursNotAvailable` operationId).
	MakeHoursNotAvailableWithResponse(ctx context.Context, body MakeHoursNotAvailableJSONRequestBody, reqEditors ...RequestEditorFn) (*MakeHoursNotAvailableClientResponse, error)
}

type GetTrainerHoursClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Date
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidInput
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetTrainerHoursClientResponse) GetJSON200() *[]Date {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetTrainerHoursClientResponse) GetJSON400() *InvalidInput {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetTrainerHoursClientResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r GetTrainerHoursClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetTrainerHoursClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTrainerHoursClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTrainerHoursClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type MakeHoursAvailableClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidInput
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r MakeHoursAvailableClientResponse) GetJSON400() *InvalidInput {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r MakeHoursAvailableClientResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r MakeHoursAvailableClientResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r MakeHoursAvailableClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r MakeHoursAvailableClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MakeHoursAvailableClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MakeHoursAvailableClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type MakeHoursNotAvailableClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidInput
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r MakeHoursNotAvailableClientResponse) GetJSON400() *InvalidInput {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r MakeHoursNotAvailableClientResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r MakeHoursNotAvailableClientResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r MakeHoursNotAvailableClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r MakeHoursNotAvailableClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MakeHoursNotAvailableClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MakeHoursNotAvailableClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetTrainerHoursWithResponse Get the trainer's hours in a date range
//
// Returns every day from `from` to `to` (both inclusive, in UTC), each with all the hours between the minimum and maximum UTC hour. Hours that are not stored are returned as not available.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/trainer/hours (the `GetTrainerHours` operationId).
func (c *ClientWithResponses) GetTrainerHoursWithResponse(ctx context.Context, params *GetTrainerHoursParams, reqEditors ...RequestEditorFn) (*GetTrainerHoursClientResponse, error) {
	rsp, err := c.GetTrainerHours(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTrainerHoursClientResponse(rsp)
}

// MakeHoursAvailableWithBodyWithResponse Make hours available
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/trainer/hours/available (the `MakeHoursAvailable` operationId).
func (c *ClientWithResponses) MakeHoursAvailableWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MakeHoursAvailableClientResponse, error) {
	rsp, err := c.MakeHoursAvailableWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMakeHoursAvailableClientResponse(rsp)
}

// MakeHoursAvailableWithResponse Make hours available
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/trainer/hours/available (the `MakeHoursAvailable` operationId).
func (c *ClientWithResponses) MakeHoursAvailableWithResponse(ctx context.Context, body MakeHoursAvailableJSONRequestBody, reqEditors ...RequestEditorFn) (*MakeHoursAvailableClientResponse, error) {
	rsp, err := c.MakeHoursAvailable(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMakeHoursAvailableClientResponse(rsp)
}

// MakeHoursNotAvailableWithBodyWithResponse Make hours not available
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/trainer/hours/not-available (the `MakeHoursNotAvailable` operationId).
func (c *ClientWithResponses) MakeHoursNotAvailableWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MakeHoursNotAvailableClientResponse, error) {
	rsp, err := c.MakeHoursNotAvailableWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMakeHoursNotAvailableClientResponse(rsp)
}

// MakeHoursNotAvailableWithResponse Make hours not available
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /api/v1/trainer/hours/not-available (the `MakeHoursNotAvailable` operationId).
func (c *ClientWithResponses) MakeHoursNotAvailableWithResponse(ctx context.Context, body MakeHoursNotAvailableJSONRequestBody, reqEditors ...RequestEditorFn) (*MakeHoursNotAvailableClientResponse, error) {
	rsp, err := c.MakeHoursNotAvailable(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMakeHoursNotAvailableClientResponse(rsp)
}

// ParseGetTrainerHoursClientResponse parses an HTTP response from a GetTrainerHoursWithResponse call
func ParseGetTrainerHoursClientResponse(rsp *http.Response) (*GetTrainerHoursClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTrainerHoursClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Date
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidInput
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseMakeHoursAvailableClientResponse parses an HTTP response from a MakeHoursAvailableWithResponse call
func ParseMakeHoursAvailableClientResponse(rsp *http.Response) (*MakeHoursAvailableClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MakeHoursAvailableClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidInput
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseMakeHoursNotAvailableClientResponse parses an HTTP response from a MakeHoursNotAvailableWithResponse call
func ParseMakeHoursNotAvailableClientResponse(rsp *http.Response) (*MakeHoursNotAvailableClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MakeHoursNotAvailableClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidInput
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}
