// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package http

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`

	// Total Number of items across all pages
	Total int `json:"total"`
}

// ScheduleTrainingRequest defines model for ScheduleTrainingRequest.
type ScheduleTrainingRequest struct {
	Hour            time.Time `json:"hour"`
	Notes           string    `json:"notes"`
	TrainerUsername string    `json:"trainerUsername"`
	TrainerUuid     string    `json:"trainerUuid"`
}

// ScheduledTraining defines model for ScheduledTraining.
type ScheduledTraining struct {
	Uuid string `json:"uuid"`
}

// Training defines model for Training.
type Training struct {
	AttendeeUsername string    `json:"attendeeUsername"`
	AttendeeUuid     string    `json:"attendeeUuid"`
	Canceled         bool      `json:"canceled"`
	Hour             time.Time `json:"hour"`
	Notes            string    `json:"notes"`

	// ProposedBy Uuid of the user who proposed the reschedule, set together with proposedNewTime
	ProposedBy *string `json:"proposedBy,omitempty"`

	// ProposedByUsername Username of proposedBy; absent for proposals stored before usernames existed
	ProposedByUsername *string `json:"proposedByUsername,omitempty"`

	// ProposedNewTime Set while a reschedule is waiting for approval
	ProposedNewTime *time.Time `json:"proposedNewTime,omitempty"`
	TrainerUsername string     `json:"trainerUsername"`
	TrainerUuid     string     `json:"trainerUuid"`
	Uuid            string     `json:"uuid"`
}

// TrainingsPage defines model for TrainingsPage.
type TrainingsPage struct {
	Items      []Training `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InvalidInput defines model for InvalidInput.
type InvalidInput = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetUserTrainingsParams defines parameters for GetUserTrainings.
type GetUserTrainingsParams struct {
	// Page Page number, starting at 1
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of trainings per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ScheduleTrainingJSONRequestBody defines body for ScheduleTraining for application/json ContentType.
type ScheduleTrainingJSONRequestBody = ScheduleTrainingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetUserTrainings Get the user's upcoming trainings
	// (GET /api/v1/trainings)
	GetUserTrainings(ctx *echo.Context, params GetUserTrainingsParams) error
	// ScheduleTraining Schedule a training
	// (POST /api/v1/trainings)
	ScheduleTraining(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetUserTrainings converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserTrainings(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserTrainingsParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", ctx.QueryParams(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageSize: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserTrainings(ctx, params)
	return err
}

// ScheduleTraining converts echo context to params.
func (w *ServerInterfaceWrapper) ScheduleTraining(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ScheduleTraining(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/api/v1/trainings", wrapper.GetUserTrainings, options.OperationMiddlewares["getUserTrainings"]...)
	router.POST(options.BaseURL+"/api/v1/trainings", wrapper.ScheduleTraining, options.OperationMiddlewares["scheduleTraining"]...)

}

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type InvalidInputJSONResponse Error

type UnauthorizedJSONResponse Error

type GetUserTrainingsRequestObject struct {
	Params GetUserTrainingsParams
}

type GetUserTrainingsResponseObject interface {
	VisitGetUserTrainingsResponse(w http.ResponseWriter) error
}

type GetUserTrainings200JSONResponse TrainingsPage

func (response GetUserTrainings200JSONResponse) VisitGetUserTrainingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserTrainings400JSONResponse struct{ InvalidInputJSONResponse }

func (response GetUserTrainings400JSONResponse) VisitGetUserTrainingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserTrainings401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUserTrainings401JSONResponse) VisitGetUserTrainingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ScheduleTrainingRequestObject struct {
	Body *ScheduleTrainingJSONRequestBody
}

type ScheduleTrainingResponseObject interface {
	VisitScheduleTrainingResponse(w http.ResponseWriter) error
}

type ScheduleTraining201JSONResponse ScheduledTraining

func (response ScheduleTraining201JSONResponse) VisitScheduleTrainingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type ScheduleTraining400JSONResponse struct{ InvalidInputJSONResponse }

func (response ScheduleTraining400JSONResponse) VisitScheduleTrainingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ScheduleTraining401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ScheduleTraining401JSONResponse) VisitScheduleTrainingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ScheduleTraining403JSONResponse struct{ ForbiddenJSONResponse }

func (response ScheduleTraining403JSONResponse) VisitScheduleTrainingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ScheduleTraining409JSONResponse struct{ ConflictJSONResponse }

func (response ScheduleTraining409JSONResponse) VisitScheduleTrainingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetUserTrainings Get the user's upcoming trainings
	// (GET /api/v1/trainings)
	GetUserTrainings(ctx context.Context, request GetUserTrainingsRequestObject) (GetUserTrainingsResponseObject, error)
	// ScheduleTraining Schedule a training
	// (POST /api/v1/trainings)
	ScheduleTraining(ctx context.Context, request ScheduleTrainingRequestObject) (ScheduleTrainingResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetUserTrainings operation middleware
func (sh *strictHandler) GetUserTrainings(ctx *echo.Context, params GetUserTrainingsParams) error {
	var request GetUserTrainingsRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserTrainings(ctx.Request().Context(), request.(GetUserTrainingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserTrainings")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserTrainingsResponseObject); ok {
		return validResponse.VisitGetUserTrainingsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ScheduleTraining operation middleware
func (sh *strictHandler) ScheduleTraining(ctx *echo.Context) error {
	var request ScheduleTrainingRequestObject

	var body ScheduleTrainingJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ScheduleTraining(ctx.Request().Context(), request.(ScheduleTrainingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ScheduleTraining")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ScheduleTrainingResponseObject); ok {
		return validResponse.VisitScheduleTrainingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
