// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmodels

import (
	"time"

	"backend/internal/trainings/domain"
)

type TrainingsTraining struct {
	ID               domain.TrainingUUID
	Hour             time.Time
	Notes            string
	AttendeeID       string
	AttendeeUsername string
	TrainerID        string
	TrainerUsername  string
	ProposedNewTime  *time.Time
	MoveProposedByID *string
	Canceled         bool
}
