// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trainings.sql

package dbmodels

import (
	"context"
	"time"

	"backend/internal/trainings/domain"
)

const getTraining = `-- name: GetTraining :one
SELECT id, hour, notes, attendee_id, attendee_username, trainer_id, trainer_username, proposed_new_time, move_proposed_by_id, canceled
FROM trainings.trainings
WHERE id = $1
`

func (q *Queries) GetTraining(ctx context.Context, id domain.TrainingUUID) (TrainingsTraining, error) {
	row := q.db.QueryRow(ctx, getTraining, id)
	var i TrainingsTraining
	err := row.Scan(
		&i.ID,
		&i.Hour,
		&i.Notes,
		&i.AttendeeID,
		&i.AttendeeUsername,
		&i.TrainerID,
		&i.TrainerUsername,
		&i.ProposedNewTime,
		&i.MoveProposedByID,
		&i.Canceled,
	)
	return i, err
}

const upsertTraining = `-- name: UpsertTraining :exec
INSERT INTO trainings.trainings (
    id, hour, notes,
    attendee_id, attendee_username,
    trainer_id, trainer_username,
    proposed_new_time, move_proposed_by_id,
    canceled
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10
)
ON CONFLICT (id)
DO UPDATE
SET hour = EXCLUDED.hour,
    notes = EXCLUDED.notes,
    proposed_new_time = EXCLUDED.proposed_new_time,
    move_proposed_by_id = EXCLUDED.move_proposed_by_id,
    canceled = EXCLUDED.canceled
`

type UpsertTrainingParams struct {
	ID               domain.TrainingUUID
	Hour             time.Time
	Notes            string
	AttendeeID       string
	AttendeeUsername string
	TrainerID        string
	TrainerUsername  string
	ProposedNewTime  *time.Time
	MoveProposedByID *string
	Canceled         bool
}

func (q *Queries) UpsertTraining(ctx context.Context, arg UpsertTrainingParams) error {
	_, err := q.db.Exec(ctx, upsertTraining,
		arg.ID,
		arg.Hour,
		arg.Notes,
		arg.AttendeeID,
		arg.AttendeeUsername,
		arg.TrainerID,
		arg.TrainerUsername,
		arg.ProposedNewTime,
		arg.MoveProposedByID,
		arg.Canceled,
	)
	return err
}
