// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trainings_read_model.sql

package dbmodels

import (
	"context"
	"time"
)

const countUpcomingTrainingsByUser = `-- name: CountUpcomingTrainingsByUser :one
SELECT count(*)
FROM trainings.trainings
WHERE (attendee_id = $1 OR trainer_id = $1)
    AND hour > $2::timestamptz
`

type CountUpcomingTrainingsByUserParams struct {
	UserID string
	After  time.Time
}

func (q *Queries) CountUpcomingTrainingsByUser(ctx context.Context, arg CountUpcomingTrainingsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUpcomingTrainingsByUser, arg.UserID, arg.After)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUpcomingTrainingsByUser = `-- name: GetUpcomingTrainingsByUser :many
SELECT id, hour, notes, attendee_id, attendee_username, trainer_id, trainer_username, proposed_new_time, move_proposed_by_id, canceled
FROM trainings.trainings
WHERE (attendee_id = $1 OR trainer_id = $1)
    AND hour > $2::timestamptz
ORDER BY hour, id
LIMIT $4::bigint
OFFSET $3::bigint
`

type GetUpcomingTrainingsByUserParams struct {
	UserID     string
	After      time.Time
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) GetUpcomingTrainingsByUser(ctx context.Context, arg GetUpcomingTrainingsByUserParams) ([]TrainingsTraining, error) {
	rows, err := q.db.Query(ctx, getUpcomingTrainingsByUser,
		arg.UserID,
		arg.After,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingsTraining{}
	for rows.Next() {
		var i TrainingsTraining
		if err := rows.Scan(
			&i.ID,
			&i.Hour,
			&i.Notes,
			&i.AttendeeID,
			&i.AttendeeUsername,
			&i.TrainerID,
			&i.TrainerUsername,
			&i.ProposedNewTime,
			&i.MoveProposedByID,
			&i.Canceled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
