/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppSetScheduleRouteImport } from './routes/_app/set-schedule'
import { Route as AppTrainingsRouteImport } from './routes/_app/trainings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSetScheduleRoute = AppSetScheduleRouteImport.update({
  id: '/set-schedule',
  path: '/set-schedule',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTrainingsRoute = AppTrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/set-schedule': typeof AppSetScheduleRoute
  '/trainings': typeof AppTrainingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/set-schedule': typeof AppSetScheduleRoute
  '/trainings': typeof AppTrainingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/set-schedule': typeof AppSetScheduleRoute
  '/_app/trainings': typeof AppTrainingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/set-schedule' | '/trainings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/set-schedule' | '/trainings'
  id: '__root__' | '/' | '/_app' | '/_app/set-schedule' | '/_app/trainings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/set-schedule': {
      id: '/_app/set-schedule'
      path: '/set-schedule'
      fullPath: '/set-schedule'
      preLoaderRoute: typeof AppSetScheduleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/trainings': {
      id: '/_app/trainings'
      path: '/trainings'
      fullPath: '/trainings'
      preLoaderRoute: typeof AppTrainingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppSetScheduleRoute: typeof AppSetScheduleRoute
  AppTrainingsRoute: typeof AppTrainingsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSetScheduleRoute: AppSetScheduleRoute,
  AppTrainingsRoute: AppTrainingsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
