// Package clients provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package clients

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`

	// Total Number of items across all pages
	Total int `json:"total"`
}

// ScheduleTrainingRequest defines model for ScheduleTrainingRequest.
type ScheduleTrainingRequest struct {
	Hour            time.Time `json:"hour"`
	Notes           string    `json:"notes"`
	TrainerUsername string    `json:"trainerUsername"`
	TrainerUuid     string    `json:"trainerUuid"`
}

// ScheduledTraining defines model for ScheduledTraining.
type ScheduledTraining struct {
	Uuid string `json:"uuid"`
}

// Training defines model for Training.
type Training struct {
	AttendeeUsername string    `json:"attendeeUsername"`
	AttendeeUuid     string    `json:"attendeeUuid"`
	Canceled         bool      `json:"canceled"`
	Hour             time.Time `json:"hour"`
	Notes            string    `json:"notes"`

	// ProposedBy Uuid of the user who proposed the reschedule, set together with proposedNewTime
	ProposedBy *string `json:"proposedBy,omitempty"`

	// ProposedByUsername Username of proposedBy; absent for proposals stored before usernames existed
	ProposedByUsername *string `json:"proposedByUsername,omitempty"`

	// ProposedNewTime Set while a reschedule is waiting for approval
	ProposedNewTime *time.Time `json:"proposedNewTime,omitempty"`
	TrainerUsername string     `json:"trainerUsername"`
	TrainerUuid     string     `json:"trainerUuid"`
	Uuid            string     `json:"uuid"`
}

// TrainingsPage defines model for TrainingsPage.
type TrainingsPage struct {
	Items      []Training `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InvalidInput defines model for InvalidInput.
type InvalidInput = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetUserTrainingsParams defines parameters for GetUserTrainings.
type GetUserTrainingsParams struct {
	// Page Page number, starting at 1
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of trainings per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ScheduleTrainingJSONRequestBody defines body for ScheduleTraining for application/json ContentType.
type ScheduleTrainingJSONRequestBody = ScheduleTrainingRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetUserTrainings Get the user's upcoming trainings
	//
	// Returns the trainings, soonest first, where the user from the session is the trainer or the attendee. Only trainings after now are returned, including canceled ones (see `canceled`). The list is paginated with `page` and `pageSize`; `total` is the number of trainings across all pages.
	//
	// Corresponds with GET /api/v1/trainings (the `GetUserTrainings` operationId).
	GetUserTrainings(ctx context.Context, params *GetUserTrainingsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ScheduleTrainingWithBody Schedule a training
	//
	// The attendee (taken from the session) books the trainer's hour. The hour must be available.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1/trainings (the `ScheduleTraining` operationId).
	ScheduleTrainingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ScheduleTraining Schedule a training
	//
	// The attendee (taken from the session) books the trainer's hour. The hour must be available.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1/trainings (the `ScheduleTraining` operationId).
	ScheduleTraining(ctx context.Context, body ScheduleTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelTraining Cancel a training
	//
	// The trainer or the attendee (taken from the session) cancels the training and the trainer's hour becomes available again. The attendee gets the credit back when the training is canceled at least 24 hours before the hour.
	//
	// Corresponds with POST /api/v1/trainings/{trainingUuid}/cancel (the `CancelTraining` operationId).
	CancelTraining(ctx context.Context, trainingUuid string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetUserTrainings Get the user's upcoming trainings
//
// Returns the trainings, soonest first, where the user from the session is the trainer or the attendee. Only trainings after now are returned, including canceled ones (see `canceled`). The list is paginated with `page` and `pageSize`; `total` is the number of trainings across all pages.
//
// Corresponds with GET /api/v1/trainings (the `GetUserTrainings` operationId).
func (c *Client) GetUserTrainings(ctx context.Context, params *GetUserTrainingsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserTrainingsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ScheduleTrainingWithBody Schedule a training
//
// The attendee (taken from the session) books the trainer's hour. The hour must be available.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1/trainings (the `ScheduleTraining` operationId).
func (c *Client) ScheduleTrainingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewScheduleTrainingRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ScheduleTraining Schedule a training
//
// The attendee (taken from the session) books the trainer's hour. The hour must be available.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1/trainings (the `ScheduleTraining` operationId).
func (c *Client) ScheduleTraining(ctx context.Context, body ScheduleTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewScheduleTrainingRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CancelTraining Cancel a training
//
// The trainer or the attendee (taken from the session) cancels the training and the trainer's hour becomes available again. The attendee gets the credit back when the training is canceled at least 24 hours before the hour.
//
// Corresponds with POST /api/v1/trainings/{trainingUuid}/cancel (the `CancelTraining` operationId).
func (c *Client) CancelTraining(ctx context.Context, trainingUuid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelTrainingRequest(c.Server, trainingUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetUserTrainingsRequest constructs an http.Request for the GetUserTrainings method
func NewGetUserTrainingsRequest(server string, params *GetUserTrainingsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/trainings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pageSize", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewScheduleTrainingRequest calls the generic ScheduleTraining builder with application/json body
func NewScheduleTrainingRequest(server string, body ScheduleTrainingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewScheduleTrainingRequestWithBody(server, "application/json", bodyReader)
}

// NewScheduleTrainingRequestWithBody constructs an http.Request for the ScheduleTraining method, with any body, and a specified content type
func NewScheduleTrainingRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/trainings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCancelTrainingRequest constructs an http.Request for the CancelTraining method
func NewCancelTrainingRequest(server string, trainingUuid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "trainingUuid", trainingUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/trainings/%s/cancel", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetUserTrainingsWithResponse Get the user's upcoming trainings
	//
	// Returns the trainings, soonest first, where the user from the session is the trainer or the attendee. Only trainings after now are returned, including canceled ones (see `canceled`). The list is paginated with `page` and `pageSize`; `total` is the number of trainings across all pages.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/trainings (the `GetUserTrainings` operationId).
	GetUserTrainingsWithResponse(ctx context.Context, params *GetUserTrainingsParams, reqEditors ...RequestEditorFn) (*GetUserTrainingsClientResponse, error)

	// ScheduleTrainingWithBodyWithResponse Schedule a training
	//
	// The attendee (taken from the session) books the trainer's hour. The hour must be available.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/trainings (the `ScheduleTraining` operationId).
	ScheduleTrainingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ScheduleTrainingClientResponse, error)

	// ScheduleTrainingWithResponse Schedule a training
	//
	// The attendee (taken from the session) books the trainer's hour. The hour must be available.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/trainings (the `ScheduleTraining` operationId).
	ScheduleTrainingWithResponse(ctx context.Context, body ScheduleTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*ScheduleTrainingClientResponse, error)

	// CancelTrainingWithResponse Cancel a training
	//
	// The trainer or the attendee (taken from the session) cancels the training and the trainer's hour becomes available again. The attendee gets the credit back when the training is canceled at least 24 hours before the hour.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1/trainings/{trainingUuid}/cancel (the `CancelTraining` operationId).
	CancelTrainingWithResponse(ctx context.Context, trainingUuid string, reqEditors ...RequestEditorFn) (*CancelTrainingClientResponse, error)
}

type GetUserTrainingsClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *TrainingsPage
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidInput
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetUserTrainingsClientResponse) GetJSON200() *TrainingsPage {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetUserTrainingsClientResponse) GetJSON400() *InvalidInput {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetUserTrainingsClientResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r GetUserTrainingsClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetUserTrainingsClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserTrainingsClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetUserTrainingsClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ScheduleTrainingClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *ScheduledTraining
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidInput
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r ScheduleTrainingClientResponse) GetJSON201() *ScheduledTraining {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ScheduleTrainingClientResponse) GetJSON400() *InvalidInput {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ScheduleTrainingClientResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r ScheduleTrainingClientResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r ScheduleTrainingClientResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r ScheduleTrainingClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ScheduleTrainingClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ScheduleTrainingClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ScheduleTrainingClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CancelTrainingClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidInput
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CancelTrainingClientResponse) GetJSON400() *InvalidInput {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CancelTrainingClientResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r CancelTrainingClientResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CancelTrainingClientResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CancelTrainingClientResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r CancelTrainingClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CancelTrainingClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelTrainingClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CancelTrainingClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetUserTrainingsWithResponse Get the user's upcoming trainings
//
// Returns the trainings, soonest first, where the user from the session is the trainer or the attendee. Only trainings after now are returned, including canceled ones (see `canceled`). The list is paginated with `page` and `pageSize`; `total` is the number of trainings across all pages.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/trainings (the `GetUserTrainings` operationId).
func (c *ClientWithResponses) GetUserTrainingsWithResponse(ctx context.Context, params *GetUserTrainingsParams, reqEditors ...RequestEditorFn) (*GetUserTrainingsClientResponse, error) {
	rsp, err := c.GetUserTrainings(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserTrainingsClientResponse(rsp)
}

// ScheduleTrainingWithBodyWithResponse Schedule a training
//
// The attendee (taken from the session) books the trainer's hour. The hour must be available.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/trainings (the `ScheduleTraining` operationId).
func (c *ClientWithResponses) ScheduleTrainingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ScheduleTrainingClientResponse, error) {
	rsp, err := c.ScheduleTrainingWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseScheduleTrainingClientResponse(rsp)
}

// ScheduleTrainingWithResponse Schedule a training
//
// The attendee (taken from the session) books the trainer's hour. The hour must be available.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/trainings (the `ScheduleTraining` operationId).
func (c *ClientWithResponses) ScheduleTrainingWithResponse(ctx context.Context, body ScheduleTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*ScheduleTrainingClientResponse, error) {
	rsp, err := c.ScheduleTraining(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseScheduleTrainingClientResponse(rsp)
}

// CancelTrainingWithResponse Cancel a training
//
// The trainer or the attendee (taken from the session) cancels the training and the trainer's hour becomes available again. The attendee gets the credit back when the training is canceled at least 24 hours before the hour.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1/trainings/{trainingUuid}/cancel (the `CancelTraining` operationId).
func (c *ClientWithResponses) CancelTrainingWithResponse(ctx context.Context, trainingUuid string, reqEditors ...RequestEditorFn) (*CancelTrainingClientResponse, error) {
	rsp, err := c.CancelTraining(ctx, trainingUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelTrainingClientResponse(rsp)
}

// ParseGetUserTrainingsClientResponse parses an HTTP response from a GetUserTrainingsWithResponse call
func ParseGetUserTrainingsClientResponse(rsp *http.Response) (*GetUserTrainingsClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserTrainingsClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TrainingsPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidInput
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseScheduleTrainingClientResponse parses an HTTP response from a ScheduleTrainingWithResponse call
func ParseScheduleTrainingClientResponse(rsp *http.Response) (*ScheduleTrainingClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ScheduleTrainingClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ScheduledTraining
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidInput
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseCancelTrainingClientResponse parses an HTTP response from a CancelTrainingWithResponse call
func ParseCancelTrainingClientResponse(rsp *http.Response) (*CancelTrainingClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelTrainingClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidInput
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}
